/**
 * Structured logging helper.
 *
 * RES-04 — every API route used to call `console.error('[meta-poll] ...', err)`,
 * `console.warn('[paypal] ...', { ctx })`, etc. Each line was a free-form
 * string that Vercel's log search couldn't filter consistently. With many
 * users + many routes the only way to correlate "this user reported they
 * never got premium" was to grep timestamps.
 *
 * This helper emits a single JSON line per call. Vercel and most log
 * shippers (Datadog, Logtail, axiom) auto-parse JSON and let the operator
 * filter on `level`, `route`, `request_id`, `user_id`, etc. The format is
 * deliberately minimal — no fancy library, no async transports, no global
 * state — so it works inside `after()` callbacks and crons identically.
 *
 * The `request_id` is generated by `proxy.ts` for every page request and
 * propagated via the `x-request-id` header. API routes can read it from
 * the inbound `Request.headers` and pass it into the logger so all log
 * lines from a single request share the same id.
 *
 * Usage:
 *
 *   import { log } from '@/lib/log'
 *   log.info('paypal/confirm', 'subscription activated', {
 *     request_id: req.headers.get('x-request-id'),
 *     subscription_id: subscriptionId,
 *     profile_id: profileId,
 *   })
 *
 *   log.error('cron/sync', 'profile update failed', {
 *     request_id: '...',
 *     err: err instanceof Error ? err.message : String(err),
 *   })
 *
 * The first arg is a route/component identifier; the second is a short
 * human-readable message; the third is structured context. Keep keys
 * stable across log lines so dashboards can group by them.
 */

export type LogLevel = 'debug' | 'info' | 'warn' | 'error'

export interface LogContext {
  request_id?: string | null
  user_id?: string | null
  err?: unknown
  [key: string]: unknown
}

function emit(level: LogLevel, scope: string, message: string, ctx: LogContext = {}): void {
  // Serialise `err` defensively — Error objects don't JSON.stringify nicely.
  let errPayload: unknown = ctx.err
  if (errPayload instanceof Error) {
    errPayload = {
      name: errPayload.name,
      message: errPayload.message,
      // Stack only in non-production to avoid leaking source paths in prod logs.
      ...(process.env.NODE_ENV !== 'production' ? { stack: errPayload.stack } : {}),
    }
  }
  const { err, request_id, user_id, ...rest } = ctx
  void err  // consumed above
  const line = {
    level,
    ts: new Date().toISOString(),
    scope,
    msg: message,
    ...(request_id ? { request_id } : {}),
    ...(user_id ? { user_id } : {}),
    ...(errPayload !== undefined ? { err: errPayload } : {}),
    ...rest,
  }
  // Use the appropriate console method so Vercel groups levels correctly
  // in the dashboard. JSON.stringify is robust to circular refs via the
  // replacer (JSON.stringify will throw — keep the call simple, callers
  // are expected to pass plain objects).
  const serialised = (() => {
    try {
      return JSON.stringify(line)
    } catch {
      // Fallback: drop the problematic context, keep level + msg.
      return JSON.stringify({ level, ts: line.ts, scope, msg: message, _ctx_serialise_failed: true })
    }
  })()
  switch (level) {
    case 'error':
      console.error(serialised)
      break
    case 'warn':
      console.warn(serialised)
      break
    case 'info':
      console.log(serialised)
      break
    case 'debug':
      // Only emit debug in non-production to avoid log noise + cost.
      if (process.env.NODE_ENV !== 'production') console.debug(serialised)
      break
  }
}

export const log = {
  debug: (scope: string, msg: string, ctx?: LogContext) => emit('debug', scope, msg, ctx),
  info: (scope: string, msg: string, ctx?: LogContext) => emit('info', scope, msg, ctx),
  warn: (scope: string, msg: string, ctx?: LogContext) => emit('warn', scope, msg, ctx),
  error: (scope: string, msg: string, ctx?: LogContext) => emit('error', scope, msg, ctx),
}

/**
 * Extract the `x-request-id` header set by `proxy.ts`. Returns `null` when
 * absent (cron routes, unit tests, manual calls) — callers should treat
 * `null` as "no correlation id available", not as an error.
 */
export function requestIdFrom(req: Request): string | null {
  return req.headers.get('x-request-id') ?? null
}
