import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/__tests__/**/*.test.{ts,tsx}'],
    // TEST-08 — coverage gate. Without thresholds a PR that adds 500 LoC
    // without tests passes silently, eroding the 870+ test investment.
    // The numbers below are deliberately CONSERVATIVE — they reflect the
    // current state, not an aspirational target. Tighten them as
    // coverage grows; never loosen.
    //
    // Run with: `npx vitest run --coverage` (locally) or via the `unit`
    // CI job once we wire `--coverage` into the workflow.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov'],
      // Generated / config / type-only / experimental files don't carry
      // executable logic worth gating on. Tests themselves are excluded
      // by default, no need to list them.
      exclude: [
        'src/__tests__/**',
        'src/test/**',
        'src/**/*.d.ts',
        'src/**/*.config.{ts,js}',
        // Generated by Next 16's dev type generator; opaque to us.
        '.next/**',
        // Public brawler-icon barrel — pure re-exports, no logic.
        'src/lib/brawler-icons.ts',
      ],
      thresholds: {
        // Locked at the current ~73% baseline. Bump as we close TEST-02
        // (8 missing route integration tests) and TEST-04 (security
        // tests directory).
        lines: 70,
        functions: 70,
        branches: 60,
        statements: 70,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
